### ISSUE TITLE
Test1 and test2 does not run: SIGSEGV: Illegal storage access.

### ISSUE THREAD

**Issue by treeform** [bung87/objc_runtime#1]
I am getting:

## Test1

```
Traceback (most recent call last)
/Users/me/p/objc_runtime/tests/test1.nim(47) test1
/Users/me/p/objc_runtime/tests/test1.nim(26) main
/Users/me/p/objc_runtime/tests/test1.nim(10) createMenuItem
/Users/me/p/objc_runtime/src/objc_runtime.nim(805) get_nsstring
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

## Test2

```
/Users/me/p/objc_runtime/tests/test2.nim(28) test2
/Users/me/p/nim/lib/system/assertions.nim(39) failedAssertImpl
/Users/me/p/nim/lib/system/assertions.nim(29) raiseAssert
/Users/me/p/nim/lib/system/fatal.nim(53) sysFatal
Error: unhandled exception: /Users/me/p/objc_runtime/tests/test2.nim(28, 14) `n.intValue() == 2`  [AssertionDefect]
Error: execution of an external program failed: '/Users/me/p/objc_runtime/tests/test2 '
```

When running the first test. Using development nim and M1 mac mini.

```
Nim Compiler Version 1.5.1 [MacOSX: arm64]
Compiled at 2021-07-11
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 3645f5fc7ae885e22cb52b9f865edf062cfb8e59
active boot switches: -d:release
```

**Comment by bung87** [comment]
I run tests on Catalina 10.15.7 without problems. no idea.

**Comment by Airr** [comment]
It seems like it may be an issue with the macOS arm64 development environment implementation (as it relates to objc_msgSend), because when I force compilation to x64 (pragma below, place it after the import statements and make sure you have Rosetta 2 installed), it works.

{.passC: "-target x86_64-apple-macos10.12".}
{.passL: "-target x86_64-apple-macos10.12".}

**Comment by jdf-id-au** [comment]
Could it be something to do with [this](https://github.com/jimon/osx_app_in_plain_c/blob/master/main.c#L41)? (maybe [new prototype for `objc_msgSend`](https://www.mikeash.com/pyblog/objc_msgsends-new-prototype.html))

**Comment by bung87** [comment]
dont know how to handle this, and I have no m1 mac.

**Comment by bung87** [comment]
confirmed on my new m1 MBP, have no easy fix I think.

> Could it be something to do with [this](https://github.com/jimon/osx_app_in_plain_c/blob/master/main.c#L41)? (maybe [new prototype for `objc_msgSend`](https://www.mikeash.com/pyblog/objc_msgsends-new-prototype.html))

**Comment by bung87** [comment]
I just confirmed the program works fine with Nim Compiler Version 1.9.5 [MacOSX: amd64]

so current solution is switch to Nim devel

**Comment by bung87** [comment]
now runs fine on 1.6.12 arm64 , except `objcr: [NSNumber numberWithInt:2'i32]` not works as expected, changed to `NSNumber.withInt(2'i32)` , feel free to reopen if there's problem.
